services:
   pihole:
     container_name: pihole
     image: pihole/pihole:latest
     network_mode: host 
     ports:
       # DNS Ports
       - "53:53/tcp"
       - "53:53/udp"
       # Default HTTP Port
       - "80:80/tcp"
       # Default HTTPs Port. FTL will generate a self-signed certificate
       - "443:443/tcp"
       # Uncomment the line below if you are using Pi-hole as your DHCP server
       - "67:67/udp"
       # Uncomment the line below if you are using Pi-hole as your NTP server
       - "123:123/udp"
         #env_file: ".env"
     volumes:
       - './etc-pihole:/etc/pihole'
     cap_add:
       - NET_ADMIN
       - SYS_TIME
       - SYS_NICE
     restart: unless-stopped
